---

- name: Get hostname and IP address
  hosts: all
  gather_facts: yes
  tasks:
    - name: ping
      ansible.builtin.ping:
        data: crash
    - name: Display hostname and IP address
      debug:
        msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"
