---

- name: Get hostname and IP address
  hosts: all
  ignore_unreachable: yes
  any_errors_fatal: false
  become: yes
  gather_facts: yes
  tasks:
    - name: ping
      block:
        - name: ping
          shell: ping -c 1 1.1.1.1
          register: ping_rc
          ignore_errors: true
        - name: ping out var
          debug: var=ping_rc
        - name: ping out msg
          debug: msg="{{ping_rc.stdout_lines}}"
    - name: Display hostname and IP address
      debug:
        msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"
